export const initDataProjectList = {
	projects: [
		{
			project_id: 1,
			project_name: 'project_1',
			sectionOder: [1, 3, 2],
			sections: [
				{
					section_id: 4,
					section_name: 'section 4',
					taskOder: [9, 10],
					tasks: [
						{
							task_id: 9,
							task_name: 'task_1',
							assignee_to: 'Tuan@111.com',
							due_date: 'Tue Jul 26 2022',
							priority: '1',
							created_by: 'tuan@gmail.com',
							task_progress: 2,
							status: true,
						},
						{
							task_id: 10,
							task_name: 'task_2',
							assignee_to: 'Tuan@1121.com',
							due_date: 'Wed Jul 27 2022',
							priority: 3,
							created_by: 'man@gmail.com',
							task_progress: 0,
							status: false,
						},
					],
				},
				{
					section_id: 1,
					section_name: 'section 1',
					taskOder: [1, 2],
					tasks: [
						{
							task_id: 1,
							task_name: 'task_1',
							assignee_to: 'Tuan@111.com',
							due_date: 'Sat Jul 16 2022',
							priority: 1,
							created_by: 'tuan@gmail.com',
							task_progress: 3,
							status: false,
						},
						{
							task_id: 2,
							task_name: 'task_2',
							assignee_to: 'Tuan@1121.com',
							due_date: 'Fri Jul 22 2022',
							priority: 2,
							created_by: 'thanh@gmail.com',
							task_progress: 3,
							status: true,
						},
					],
				},
				{
					section_id: 2,
					section_name: 'section 2',
					taskOder: [4, 3],
					tasks: [
						{
							task_id: 3,
							task_name: 'task_3',
							assignee_to: 'Thanh@111.com',
							due_date: 'Fri Jul 01 2022',
							priority: 1,
							created_by: 'thanh@222.com',
							task_progress: 0,
							status: true,
						},
						{
							task_id: 4,
							task_name: 'task_4',
							assignee_to: 'thanh@1121.com',
							due_date: '',
							priority: 1,
							created_by: 'man@gmail.com',
							task_progress: 2,
							status: true,
						},
					],
				},
				{
					section_id: 3,
					section_name: 'section 3',
					taskOder: [7, 6, 5],
					tasks: [
						{
							task_id: 5,
							task_name: 'task_5',
							assignee_to: 'Tuan@111.com',
							due_date: 'Fri Jul 01 2022',
							priority: 2,
							created_by: 'tuan@gmail.com',
							task_progress: 2,
							status: false,
						},
						{
							task_id: 6,
							task_name: 'task_6',
							assignee_to: 'Tuan@1121.com',
							due_date: '',
							priority: 3,
							created_by: 'thanh@gmail.com',
							task_progress: 1,
							status: true,
						},
						{
							task_id: 7,
							task_name: 'task_7',
							assignee_to: 'Tuan@1121.com',
							due_date: 'Wed Jul 06 2022',
							priority: 0,
							created_by: 'hoang@gmail.com',
							task_progress: 3,
							status: false,
						},
					],
				},
			],
		},
	],
};
