export const GET_ALL_TASK_IN_PROJECT = 'GET_ALL_TASK_IN_PROJECT';
export const GET_ALL_TASK_ORDER_IN_PROJECT = 'GET_ALL_TASK_ORDER_IN_PROJECT';
export const UPDATE_DROP_TASK = 'UPDATE_DROP_TASK';
export const UPDATE_TITLE_TASK = 'UPDATE_TITLE_TASK';
export const UPDATE_STATUS_TASK = 'UPDATE_STATUS_TASK';
export const UPDATE_TASK = 'UPDATE_TASK';
